name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - 'docs/*'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

  tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all tags - See: https://goreleaser.com/ci/actions/
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: run tests
        run: "make test"
