name: Release with changelog
on:
  push:
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - 'docs/*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all tags - See: https://goreleaser.com/ci/actions/

      - uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release -b master

  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all tags - See: https://goreleaser.com/ci/actions/
          ref: master
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: run goreleaser
        run: make goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
